### ISSUE TITLE
ganglia-monitor restart error on ubuntu 14.04

### ISSUE THREAD

**Issue by cyberflow** [ganglia/chef-ganglia#50]
in package ganglia-monitor (3.6.0) on ubuntu 14.04 initscript return exit code 1 when restart because upstart run process fastly than initscript. Generally it error of initscript which return exit code 1 when application already run.

**Comment by rocky1201** [comment]
I'm also having this exact same issue. Is it now solved?

**Comment by acqant** [comment]
+1
First it was because of process name lenght ( which man start-stop mentions ).

I shortened the name and now the -name value passed from start-stop doesn't match any process names.  It has the right pid file and pid but doesn't use it.

**Comment by cyberflow** [comment]
@acqant The https://github.com/ganglia/chef-ganglia/commit/55ed2f1f4ca863620945db8e79ec4d8a69e403dd commit have to fix it.

**Comment by acqant** [comment]
If we have the pid file why bother with the --name?  Plus name seems to to be limited to 15 chars and cookbook prepends ganglia-monitor.  Mine was ganglia-monitor-mesos-master !!!

Just take the --name no?

**Comment by cyberflow** [comment]
if you lost pid file than start-stop-daemon can to stop process by name.

**Comment by acqant** [comment]
I'll try it later today.
