### ISSUE TITLE
Merge to Chef Supermarket?

### ISSUE THREAD

**Issue by brianudwa** [ganglia/chef-ganglia#79]
Hello, there is allot of bugfixes and work that has been done on this cookbook since the 0.2.3 release. Basically the version that is on https://supermarket.chef.io/cookbooks/ganglia is broken for rpm based systems and the fixes are already incorporated into the current release. Any chance this can be bumped up to a current version in supermarket?

**Comment by maplebed** [comment]
done.  sorry it took so long.
